// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWNax8pbBgtZsb3Tx0kLxRFvtVgll3Iwk',
    appId: '1:956726569874:web:e59bfb0ad5d32910286f4b',
    messagingSenderId: '956726569874',
    projectId: 'colorist-56',
    authDomain: 'colorist-56.firebaseapp.com',
    storageBucket: 'colorist-56.firebasestorage.app',
    measurementId: 'G-D2GPD87020',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1gNTEB8g58_xH_zPyZftvsiqkJ-xMDQw',
    appId: '1:956726569874:android:e0a44253578e13e1286f4b',
    messagingSenderId: '956726569874',
    projectId: 'colorist-56',
    storageBucket: 'colorist-56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfk2djXNg_ulfdeHBMBzh99IJPQUf1L7s',
    appId: '1:956726569874:ios:bbe2489e749c2739286f4b',
    messagingSenderId: '956726569874',
    projectId: 'colorist-56',
    storageBucket: 'colorist-56.firebasestorage.app',
    iosBundleId: 'com.example.geminiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfk2djXNg_ulfdeHBMBzh99IJPQUf1L7s',
    appId: '1:956726569874:ios:bbe2489e749c2739286f4b',
    messagingSenderId: '956726569874',
    projectId: 'colorist-56',
    storageBucket: 'colorist-56.firebasestorage.app',
    iosBundleId: 'com.example.geminiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWNax8pbBgtZsb3Tx0kLxRFvtVgll3Iwk',
    appId: '1:956726569874:web:56d82145c5b9a44b286f4b',
    messagingSenderId: '956726569874',
    projectId: 'colorist-56',
    authDomain: 'colorist-56.firebaseapp.com',
    storageBucket: 'colorist-56.firebasestorage.app',
    measurementId: 'G-H0JR7K0B6X',
  );
}
